services:
  redis:
    image: redis:alpine
    container_name: hyperspace_redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf
      - ./certs/ca.crt:/etc/redis/tls/ca.crt
      - ./certs/redis.crt:/etc/redis/tls/redis.crt
      - ./certs/redis.key:/etc/redis/tls/redis.key
    restart: always
    networks:
      - selenial

  selenial-app:
    build: .
    container_name: selenial_app
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - selenial
    depends_on:
      - redis
    restart: always

networks:
  selenial:
    driver: bridge
